name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Run setup
        run: make setup

      - name: Install project
        run: make install

      - name: Lint check
        run: make lint

      - name: Run tests
        run: make test

      - name: Build
        run: make build