name: Publish to PyPI and Docker Hub

on:
  push:
    tags:
      - 'v*'  # Triggers only on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build Python package
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install --upgrade build
          python -m build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: dist/*
  
  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write

    steps:
      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-dist
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_HUB_USERNAME }}/expedia-travel-recommendations-mcp
          VERSION=${GITHUB_REF#refs/tags/v}

          # Build and tag with version and latest
          docker build -t $IMAGE:$VERSION -t $IMAGE:latest .

          # Push both tags
          docker push $IMAGE:$VERSION
          docker push $IMAGE:latest