name: Test Publish to Test PyPI

on:
 workflow_dispatch:

jobs:
  publish-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build Python package
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install --upgrade build
          python -m build

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TEST_PY_PI_TOKEN }}
